'use client';
/* eslint-disable @next/next/no-img-element */
import { createPortal } from 'react-dom';
import { useEffect } from 'react';
import { formatCurrency } from '@/lib/currency';
import type { CurrencyCode } from '@/lib/types';
import type { SkincareExportDocument, SkincareExportPdfOptions } from '@/lib/collections/skincare-exports';

const COLORS = ['#568985', '#c79232', '#6f91b6', '#8d719c', '#6e9b72', '#c47a5d', '#89939b'];
const amount = (value: number | null | undefined, currency: string) => value === null || value === undefined ? '—' : formatCurrency(value, currency as CurrencyCode);
const dateLabel = (value: Date) => value.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
function Donut({ report }: { report: SkincareExportDocument }) { const radius = 43; const circumference = 2 * Math.PI * radius; let offset = 0; if (!report.chart.segments.length) return <p className="collection-print-chart-empty">No category records are available for this breakdown.</p>; return <div className="collection-print-donut-wrap"><svg className="collection-print-donut" viewBox="0 0 120 120" role="img" aria-label="Skincare products by category"><circle cx="60" cy="60" r={radius} fill="none" stroke="#e5e7eb" strokeWidth="15" />{report.chart.segments.map(segment => { const length = circumference * segment.value / report.chart.totalProducts; const current = offset; offset += length; return <circle key={segment.label} cx="60" cy="60" r={radius} fill="none" stroke={COLORS[segment.colorIndex % COLORS.length]} strokeDasharray={`${length} ${circumference - length}`} strokeDashoffset={-current} strokeWidth="15" transform="rotate(-90 60 60)" />; })}<text x="60" y="55" textAnchor="middle" className="collection-print-donut-label">Products</text><text x="60" y="67" textAnchor="middle" className="collection-print-donut-total">{report.chart.totalProducts.toLocaleString()}</text></svg></div>; }

export default function PrintableSkincareReport({ reportDocument, pdfOptions = { includeDetails: true, includeNotes: false, includeCategoryChart: true }, onAfterPrint }: { reportDocument: SkincareExportDocument; pdfOptions?: SkincareExportPdfOptions; onAfterPrint?: () => void }) {
  useEffect(() => { document.body.classList.add('collection-print-active'); const after = () => onAfterPrint?.(); window.addEventListener('afterprint', after); const timer = window.setTimeout(() => { try { window.print(); } catch { onAfterPrint?.(); } }, 120); return () => { window.clearTimeout(timer); window.removeEventListener('afterprint', after); document.body.classList.remove('collection-print-active'); }; }, [onAfterPrint]);
  const { summary } = reportDocument;
  return createPortal(<div className="collection-print-portal" aria-hidden="true"><article className="collection-print-document"><header className="collection-print-header"><img className="collection-print-logo" src="/icons/caizen-primary-light-3000.png" alt="Caizen" /><div><h1>Skincare Report</h1><p>{reportDocument.profileName} · {reportDocument.scopeLabel}</p></div><dl><div><dt>Generated</dt><dd>{dateLabel(reportDocument.generatedAt)}</dd></div><div><dt>Filters</dt><dd>{reportDocument.filterSummary}</dd></div></dl></header>
    <section><h2>Summary</h2><div className="collection-print-summary-strip collection-print-summary-strip--wide">{[['Products', summary.itemRecords.toLocaleString()], ['Active', summary.activeCount.toLocaleString()], ['Finished', summary.finishedCount.toLocaleString()], ['Purchase cost', amount(summary.purchaseTotal, reportDocument.currency)], ['Current/SRP', amount(summary.currentTotal, reportDocument.currency)], ['Categories', summary.categoryCount.toLocaleString()]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></section>
    <section><h2>Routine overview</h2><div className="collection-print-routine-grid">{[['Morning', reportDocument.routine.morning], ['Evening', reportDocument.routine.evening]].map(([label, products]) => <div key={label as string}><h3>{label as string}</h3>{(products as SkincareExportDocument['items']).length ? <ol>{(products as SkincareExportDocument['items']).map((item, index) => <li key={`${item.name}-${index}`}><strong>{item.name}</strong><span>{item.category} · {item.productType}</span></li>)}</ol> : <p className="collection-print-empty">No products recorded.</p>}</div>)}</div></section>
    <section><h2>Product breakdown</h2>{reportDocument.categories.length ? <div className={`collection-print-breakdown-grid${pdfOptions.includeCategoryChart ? '' : ' collection-print-breakdown-grid--table-only'}`}>{pdfOptions.includeCategoryChart ? <Donut report={reportDocument} /> : null}<div><h3>Products by category</h3><table className="collection-print-table"><thead><tr><th>Category</th><th>Products</th><th>Share</th></tr></thead><tbody>{reportDocument.categories.map(category => <tr key={category.category}><td><span className="collection-print-swatch" style={{ backgroundColor: COLORS[category.chartColorIndex % COLORS.length] }} />{category.category}</td><td>{category.itemRecords}</td><td>{category.share.toFixed(1)}%</td></tr>)}</tbody></table></div></div> : <p className="collection-print-empty">No product categories match this export.</p>}</section>
    <section><h2>Status</h2><div className="collection-print-counts"><div><strong>Active</strong><span>{summary.activeCount}</span></div><div><strong>Finished</strong><span>{summary.finishedCount}</span></div></div></section>
    {pdfOptions.includeDetails ? <section className="collection-print-details"><h2>Product details</h2>{reportDocument.items.length ? <table className="collection-print-table"><thead><tr><th>Product</th><th>Category / type</th><th>Size</th><th>Routine</th><th>Frequency</th><th>Status</th><th>Purchase</th><th>Current/SRP</th><th>Dates</th></tr></thead><tbody>{reportDocument.items.map((item, index) => <tr key={`${item.name}-${index}`}><td>{item.name}</td><td>{item.category} / {item.productType}</td><td>{item.size || '—'}</td><td>{item.schedule}</td><td>{item.frequency}</td><td>{item.status}</td><td>{amount(item.purchasePrice, reportDocument.currency)}</td><td>{amount(item.currentPrice, reportDocument.currency)}</td><td>{[item.startDate ? `Started ${item.startDate}` : '', item.finishedDate ? `Finished ${item.finishedDate}` : ''].filter(Boolean).join(' · ') || '—'}</td></tr>)}</tbody></table> : <p className="collection-print-empty">No skincare products match this export scope.</p>}</section> : null}
    {pdfOptions.includeNotes ? <section className="collection-print-notes"><h2>Notes / observations</h2>{reportDocument.items.some(item => item.notes.trim() || item.finishedNotes.trim()) ? <div>{reportDocument.items.filter(item => item.notes.trim() || item.finishedNotes.trim()).map((item, index) => <div key={`${item.name}-${index}`}><strong>{item.name}</strong>{item.notes.trim() ? <p>{item.notes}</p> : null}{item.finishedNotes.trim() ? <p><em>Finished notes:</em> {item.finishedNotes}</p> : null}</div>)}</div> : <p className="collection-print-empty">No notes are included in this export.</p>}</section> : null}
  </article></div>, document.body);
}
