'use client';
/* eslint-disable @next/next/no-img-element */
import { createPortal } from 'react-dom';
import { useEffect } from 'react';
import { formatCurrency } from '@/lib/currency';
import type { CurrencyCode } from '@/lib/types';
import type { SupplementExportDocument, SupplementExportPdfOptions } from '@/lib/collections/supplement-exports';

const amount = (value: number | null | undefined, currency: string) => value === null || value === undefined ? '—' : formatCurrency(value, currency as CurrencyCode);
const dateLabel = (value: Date) => value.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

export default function PrintableSupplementsReport({ reportDocument, pdfOptions = { includeDetails: true, includeNotes: false }, onAfterPrint }: { reportDocument: SupplementExportDocument; pdfOptions?: SupplementExportPdfOptions; onAfterPrint?: () => void }) {
  useEffect(() => { document.body.classList.add('collection-print-active'); const after = () => onAfterPrint?.(); window.addEventListener('afterprint', after); const timer = window.setTimeout(() => { try { window.print(); } catch { onAfterPrint?.(); } }, 120); return () => { window.clearTimeout(timer); window.removeEventListener('afterprint', after); document.body.classList.remove('collection-print-active'); }; }, [onAfterPrint]);
  const { summary } = reportDocument;
  return createPortal(<div className="collection-print-portal" aria-hidden="true"><article className="collection-print-document"><header className="collection-print-header"><img className="collection-print-logo" src="/icons/caizen-primary-light-3000.png" alt="Caizen" /><div><h1>Supplements Report</h1><p>{reportDocument.profileName} · {reportDocument.scopeLabel}</p></div><dl><div><dt>Generated</dt><dd>{dateLabel(reportDocument.generatedAt)}</dd></div><div><dt>Filters</dt><dd>{reportDocument.filterSummary}</dd></div></dl></header>
    <section><h2>Summary</h2><div className="collection-print-summary-strip collection-print-summary-strip--five"><div><span>Records</span><strong>{summary.itemRecords}</strong></div><div><span>Expiring soon</span><strong>{summary.expiringSoonCount}</strong></div><div><span>Reminders</span><strong>{summary.reminderCount}</strong></div><div><span>Types</span><strong>{summary.typeCount}</strong></div><div><span>Purchase cost</span><strong>{amount(summary.purchaseTotal, reportDocument.currency)}</strong></div></div></section>
    <section><h2>Schedule overview</h2>{reportDocument.schedules.length ? <table className="collection-print-table"><thead><tr><th>Schedule</th><th>Records</th><th>Products</th></tr></thead><tbody>{reportDocument.schedules.map(row => <tr key={row.schedule}><td>{row.schedule}</td><td>{row.itemRecords}</td><td>{row.products.join(', ')}</td></tr>)}</tbody></table> : <p className="collection-print-empty">No schedule records match this export.</p>}</section>
    <section><h2>Expiry and reminders</h2><div className="collection-print-counts"><div><strong>Expiring soon</strong><span>{summary.expiringSoonCount}</span></div><div><strong>Reminders enabled</strong><span>{summary.reminderCount}</span></div></div></section>
    {pdfOptions.includeDetails ? <section className="collection-print-details"><h2>Supplement details</h2>{reportDocument.items.length ? <table className="collection-print-table"><thead><tr><th>Supplement</th><th>Type</th><th>Dosage / unit</th><th>Remaining</th><th>Schedule</th><th>Start</th><th>Expiry</th><th>Purchase</th><th>Current Price</th></tr></thead><tbody>{reportDocument.items.map((item, index) => <tr key={`${item.name}-${index}`}><td>{item.name}</td><td>{item.type}</td><td>{item.dosageAmount === undefined ? item.dosageText || '—' : `${item.dosageAmount.toLocaleString()} ${item.dosageUnit || ''}`}{item.dailyIntake === undefined ? '' : ` · ${item.dailyIntake}x daily`}</td><td>{item.remaining === undefined ? '—' : item.remaining.toLocaleString()}</td><td>{item.schedule}</td><td>{item.startDate || '—'}</td><td>{item.expiryDate || '—'}</td><td>{amount(item.purchasePrice, reportDocument.currency)}</td><td>{amount(item.currentPrice, reportDocument.currency)}</td></tr>)}</tbody></table> : <p className="collection-print-empty">No supplements match this export scope.</p>}</section> : null}
    {pdfOptions.includeNotes ? <section className="collection-print-notes"><h2>Notes</h2>{reportDocument.items.some(item => item.notes.trim()) ? <div>{reportDocument.items.filter(item => item.notes.trim()).map((item, index) => <div key={`${item.name}-${index}`}><strong>{item.name}</strong><p>{item.notes}</p></div>)}</div> : <p className="collection-print-empty">No notes are included in this export.</p>}</section> : null}
  </article></div>, document.body);
}
